# Generated by Django 3.2.25 on 2026-01-09 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20240713_1117'),
        ('blog', '0003_auto_20260103_1527'),
    ]

    operations = [
    ]
